# Generated by Django 5.1.4 on 2026-07-02 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_seed_core_courses'),
        ('enrollment', '0002_schoolclass_studentprofile_school_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachercourseassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachercourseassignment',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='enrollment.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='teachercourseassignment',
            unique_together={('teacher', 'course', 'term', 'level', 'school_class')},
        ),
    ]
