# Generated by Django 6.0.4 on 2026-04-16 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_seed_core_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('VIDEO_LINK', 'Video Link'), ('PDF', 'PDF'), ('PRESENTATION', 'Presentation'), ('OTHER', 'Other')], max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.teachercourseassignment')),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
