# Generated by Django 6.0.4 on 2026-04-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolIDCounter',
            fields=[
                ('prefix', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'school_id_counters',
            },
        ),
    ]
