# Generated by Django 6.0.4 on 2026-04-18 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('ACADEMIC_PERFORMANCE', 'Academic Performance'), ('FEE_COLLECTION', 'Fee Collection'), ('TEACHER_EVALUATION', 'Teacher Evaluation')], max_length=30)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF')], max_length=5)),
                ('filters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('download_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
